### ISSUE TITLE
TCGAanalyze_Preprocessing Error

### ISSUE THREAD

**Issue by SabarinathChandrasekharan** [BioinformaticsFMRP/TCGAbiolinks#70] opened 2017-02-22 09:27 UTC
I am trying to replicate the work flow given as  GDC Downstream Pipeline --> HTSeq data: Downstream analysis BRCA in Working with TCGABiolinks

The error in the step Preprocessing is as follows

> dataPrep <- TCGAanalyze_Preprocessing(object = dataPrep, cor.cut = 0.6)
Error in TCGAanalyze_Preprocessing(object = dataPrep, cor.cut = 0.6) : 
  raw_counts not found in the assay list: HTSeq - Counts
  Please set the correct datatype argument.

I am getting the same error even after specifying the data type as datatype ="raw_counts" or as datatype ="raw_count"

Please advise.
Regards,
Sabari

**Comment by torongs82** [comment] 2017-02-22 15:34
Hi @SabarinathChandrasekharan thank you for your interest in TCGAbiolinks and thank you pointing out this feature.

I have added in our vignette this code:

dataPrep <- TCGAanalyze_Preprocessing(object = dataPrep, 
                                      cor.cut = 0.6,
                                      datatype = "HTSeq - Counts") 

Can you tell me if it is working for you?

In addition if you are interested in the assay list, you can run this:

require(SummarizedExperiment)
> assays(dataPrep)
List of length 1
names(1): HTSeq - Counts

Best,
Antonio.

**Comment by SabarinathChandrasekharan** [comment] 2017-02-23 09:13
Dear Antonio,


I see that you have changed the version from 2.2.6 to 2.2.8. But I am unable to install the new version. 

biocLite("TCGAbiolinks")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.0
  (2016-05-03).
Installing package(s) ‘TCGAbiolinks’
Warning: dependency ‘clusterProfiler’ is not available
trying URL 'https://bioconductor.org/packages/3.4/bioc/src/contrib/TCGAbiolinks_2.2.8.tar.gz'
Content type 'application/x-gzip' length 24789167 bytes (23.6 MB)
==================================================
downloaded 23.6 MB

ERROR: dependency ‘clusterProfiler’ is not available for package ‘TCGAbiolinks’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.3/TCGAbiolinks’

The downloaded source packages are in
	‘/tmp/Rtmp4bmMsz/downloaded_packages’
installation path not writeable, unable to update packages: BH,
  colorspace, digest, evaluate, formatR, ggplot2, gmp, highr,
  jsonlite, knitr, mime, plyr, R6, Rcpp, RcppEigen, RcppParallel,
  reshape2, rmarkdown, rstan, scales, shiny, StanHeaders,
  stringi, stringr, yaml, coda, DBI, rgl, rjags, RMySQL, cluster,
  codetools, foreign, lattice, Matrix, mgcv, nlme, survival
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘TCGAbiolinks’ had non-zero exit status

As well as from the GitHub

devtools::install_github(repo = "BioinformaticsFMRP/TCGAbiolinks")
Downloading GitHub repo BioinformaticsFMRP/TCGAbiolinks@master
from URL https://api.github.com/repos/BioinformaticsFMRP/TCGAbiolinks/zipball/master
Installing TCGAbiolinks
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmp4bmMsz/devtools4d87f588435/BioinformaticsFMRP-TCGAbiolinks-a1882e2'  \
  --library='/home/rstudio/R/x86_64-pc-linux-gnu-library/3.3'  \
  --install-tests 

ERROR: dependency ‘clusterProfiler’ is not available for package ‘TCGAbiolinks’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.3/TCGAbiolinks’
Error: Command failed (1)

Please advise,
Regards,
Sabari

**Comment by SabarinathChandrasekharan** [comment] 2017-02-23 10:08
Running the new vignette using the 2.2.6 version gives the following error.

query <- GDCquery(project = "TCGA-UVM",
+                   data.category = "Transcriptome Profiling",
+                   data.type = "Gene Expression Quantification", 
+                   workflow.type = "HTSeq - Counts")
Accessing GDC. This might take a while...
> samplesDown <- getResults(query,cols=c("cases"))
Error: could not find function "getResults"

**Comment by tiagochst** [comment] 2017-05-11 23:28
The problem is fixed in version higher than 2.4.0

**Closed** 2017-05-11 23:28 UTC
